apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: prod
type: Opaque
stringData:
  mongo-root-username: root
  mongo-root-password: password
  host: mongo-0.mongo-headless.prod.svc.cluster.local:27017
