
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mongo-net
  todo-api:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    image: panchanandevops/todo-spring-api:v3.0.0
    container_name: todo-api
    ports: 
      - 8080:8080
    environment:
      - spring.data.mongodb.host=mongodb
    networks:
      - mongo-net
      - frontend
    depends_on:
      - mongodb
  todo-ui:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: panchanandevops/todo-react-ui:v2.0.0
    container_name: todo-ui
    ports:
      - 3000:80
    environment:
      - REACT_APP_BACKEND_SERVER_URL=http://localhost:8080
    networks:
      - frontend
    depends_on:
      - mongodb
      - todo-api
volumes:
  # docker volume create mongo-data
  mongo-data:
    name: mongo-data
networks:
  # docker network create mongo-net
  mongo-net:
    name: mongo-net
  frontend:
    name: frontend