apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  namespace: dev
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: todo-spring-api
          image: panchanandevops/todo-spring-api:v3.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: spring.data.mongodb.host
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: host
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "64Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  namespace: dev
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
  type: ClusterIP
