apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextapp-deployment
  namespace: dev
  labels:
    app: nextapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextapp
  template:
    metadata:
      labels:
        app: nextapp
    spec:
      containers:
        - name: nextapp
          image: panchanandevops/todo-react-ui:v2.0.0
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_SERVER_URL
              value: "http://panchanandevops.com:30452"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: nextapp-service
  namespace: dev
  labels:
    app: nextapp
spec:
  selector:
    app: nextapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: ClusterIP
