apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui-deployment
  namespace: dev
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-react-ui
          image: panchanandevops/todo-react-ui:client-v0.0.3
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_SERVER_URL
              value: "http://panchanandevops.com:30452"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: todo-ui-service
  namespace: dev
  labels:
    app: todo-app
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: ClusterIP
