apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.ui-deployment.name }}
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui-deployment.replicas }}
  selector:
    matchLabels:
      {{- include "common.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Values.ui-deployment.container.name }}
          image: {{ .Values.ui-deployment.container.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.ui-deployment.container.port }}
          env:
            - name: spring.data.mongodb.host
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.secret.name }}
                  key: host
          resources:
            limits:
              memory: {{ .Values.ui-deployment.container.resources.limits.memory }}
              cpu: {{ .Values.ui-deployment.container.resources.limits.cpu }}
            requests:
              memory: {{ .Values.ui-deployment.container.resources.requests.memory }}
              cpu: {{ .Values.ui-deployment.container.resources.requests.cpu }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.uiService.name }}
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
spec:
  type: {{ .Values.uiService.type }}
  selector:
    {{- include "common.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.uiService.port }}
      targetPort: {{ .Values.ui-deployment.container.port }}
      {{- if eq .Values.uiService.type "NodePort" }}
      nodePort: {{ .Values.uiService.nodePort }}
      {{- end }}
