namespace: prod
resources:
  - ../../base
  - 6-api-ingress.yaml
  - 3-sealed-secret.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: todo-api-deployment
    path: api-patch-resources.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: todo-api-deployment
    path: api-patch-replicas.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nextapp-deployment
    path: ui-patch-resources.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nextapp-deployment
    path: ui-patch-replicas.yaml
commonLabels:
  environment: prod
